apiVersion: v1
kind: Namespace
metadata:
  name: device-plugin
---
apiVersion: v1
data:
  config.json: |
    {
      "domain": "example.com",
      "resource": {
        "name": "dev",
        "controlDevices":
        [
          {
            "containerPath": "/dev/control-device",
            "hostPath": "/dev/null"
          }
        ],
        "computeDevices":
        [
          {
            "id": "device-000",
            "containerPath": "/dev/compute-device001",
            "hostPath": "/dev/null"
          },
          {
            "id": "device-001",
            "containerPath": "/dev/compute-device002",
            "hostPath": "/dev/null"
          },
          {
            "id": "device-002",
            "containerPath": "/dev/compute-device003",
            "hostPath": "/dev/null"
          },
          {
            "id": "device-003",
            "containerPath": "/dev/compute-device004",
            "hostPath": "/dev/null"
          }
        ]
      }
    }
kind: ConfigMap
metadata:
  name: device-config
  namespace: device-plugin
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: device-plugin
  namespace: device-plugin
spec:
  selector:
    matchLabels:
      app: device-plugin
  template:
    metadata:
      labels:
        app: device-plugin
    spec:
      containers:
      - command:
        - /device-plugin
        image: device-plugin:dev
        name: device-plugin
        volumeMounts:
        - mountPath: /var/lib/kubelet/device-plugins
          name: kubelet
        - mountPath: /var/run/cdi
          name: cdi
        - mountPath: /config
          name: config
          readOnly: true
      priorityClassName: system-node-critical
      volumes:
      - hostPath:
          path: /var/lib/kubelet/device-plugins
        name: kubelet
      - hostPath:
          path: /var/run/cdi
        name: cdi
      - configMap:
          name: device-config
        name: config
