apiVersion: v1
kind: Pod
metadata:
  name: share-pod
spec:
  containers:
  - name: app
    image: ubuntu:24.04
    command: ["bash", "-c", "sleep 3600"]
    resources:
      limits:
        example.com/shared-dev: "1"
  terminationGracePeriodSeconds: 0