name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  GOPROXY: "https://proxy.golang.org,direct"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make build

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make fmt && git diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: make test

  docker:
    runs-on: ubuntu-latest
    needs: [build, fmt, test]
    steps:
      - uses: actions/checkout@v4
      - run: make docker

  e2e:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install tools
        run: make prepare
      - name: Build image & run e2e
        run: make e2e
